name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [ '1.48.0' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
            curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
            rustup toolchain install ${{ matrix.rust }}

      - name: Check Code Formatting
        run: cargo fmt -- --check

      - name: Build Code
        run: cargo build --release
